kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
  - containerPort: 443
    hostPort: 10443
  - containerPort: 2222
    hostPort: 10222
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 11080
  - containerPort: 443
    hostPort: 11443
  - containerPort: 2222
    hostPort: 11222
networking:
  apiServerAddress: "10.153.249.18"
  apiServerPort: 16443
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
