kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 20080
  - containerPort: 443
    hostPort: 20443
  - containerPort: 2222
    hostPort: 20222
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 21080
  - containerPort: 443
    hostPort: 21443
  - containerPort: 2222
    hostPort: 21222
networking:
  apiServerAddress: "10.153.249.18"
  apiServerPort: 26443
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
